apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-deployment
spec:
  selector:
    matchLabels:
      app: pod-python
  replicas: 1 
  template:
    metadata:
      labels:
        app: pod-python
    spec:
      containers:
      - name: pod-deployment
        image: 708543810688.dkr.ecr.ap-south-1.amazonaws.com/jenkins-assignment:v1
