apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-deployment
spec:
  selector:
    matchLabels:
      app: pod-python
  replicas: 1 
  template:
    metadata:
      labels:
        app: pod-python
    spec:
      containers:
      - name: pod-deployment
        image: ashishsigmoid/jenkins-assignment:v1
        ports:
        - containerPort: 5000

---


kind: Service
apiVersion: v1
metadata:
        name: pod-service
spec:
        type: LoadBalancer
        selector:
                app: pod-python
        ports:
                - port: 5000
                  targetPort: 5000


